[tool.poetry]
name = "cv2-playground"
version = "0.1.0"
description = ""
authors = ["Francoiaia <fiaia2070@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ultralytics = "^8.2.101"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
